import type { Metadata } from "next";
import "./globals.css";
import Header2 from "@/components/Header2";
import { Playfair_Display } from "next/font/google"

const playfair = Playfair_Display({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className} antialiased h-screen`}
      >
        <Header2 />
        {children}
      </body>
    </html>
  );
}
