import { render } from '@testing-library/react'
import RootLayout from '../app/layout'

// Mock Next.js font imports
jest.mock('next/font/google', () => ({
  Geist: () => ({ variable: '--font-geist-sans' }),
  Geist_Mono: () => ({ variable: '--font-geist-mono' }),
  Playfair_Display: () => ({ className: 'playfair-display' }),
}))

// Mock CSS import
jest.mock('../app/globals.css', () => ({}))

describe('RootLayout', () => {
  it('renders without crashing', () => {
    const TestChild = () => <div data-testid="test-child">Test Content</div>
    
    expect(() => {
      render(
        <RootLayout>
          <TestChild />
        </RootLayout>
      )
    }).not.toThrow()
  })

  it('renders children content', () => {
    const TestChild = () => <div data-testid="test-child">Test Content</div>
    
    const { getByTestId } = render(
      <RootLayout>
        <TestChild />
      </RootLayout>
    )
    
    expect(getByTestId('test-child')).toBeInTheDocument()
  })

  it('exports metadata correctly', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { metadata } = require('../app/layout')
    
    expect(metadata).toBeDefined()
    expect(metadata.title).toBe('Create Next App')
    expect(metadata.description).toBe('Generated by create next app')
  })
})